debug: false
problems_parent_path: data
problems_file_extension: .tsp
random_number_seed: 42
mlflow_uri: http://localhost:5000
algorithms:
  ant_system:
    iterations: 100
    alpha: 1
    beta: 2
    rho: 0.5
  min_max_ant_system:
    iterations: 1000
    stagnation_tolerance: 100
    alpha: 1
    beta: 2
    rho: 0.02
  q_learning:
    episodes: 10_000
    alpha: 0.01
    gamma: 0.6
    reward: r1
