[project]
name = "tsp-research"
version = "0.1.0"
description = "Research on state-of-the-art methods for solving the Traveling-Salesman Problem"
readme = "ReadMe.md"
requires-python = ">=3.13"
dependencies = [
    "black[d]",
    "gitpython>=3.1.44",
    "isort",
    "matplotlib>=3.10.0",
    "mlflow>=2.20.2",
    "networkx==2.8.8",
    "numpy==2.2.2",
    "optuna>=4.2.1",
    "optuna-integration[mlflow]>=4.2.1",
    "pylint>=3.3.6",
    "pyqt6>=6.8.1",
    "pytest",
    "pyyaml>=6.0.2",
    "rainbow-tqdm>=0.1.5",
    "regex>=2024.11.6",
    "ruff>=0.9.4",
    "setuptools>=75.8.0",
    "torch>=2.6.0",
    "tsplib95==0.7.1",
]
[tool.ruff.lint]
ignore = ["E741"]
