[project]
name = "tsp-research"
version = "0.1.0"
description = "Add your description here"
readme = "ReadMe.md"
requires-python = ">=3.13"
dependencies = [
    "black[d]",
    "isort",
    "matplotlib>=3.10.0",
    "networkx==2.8.8",
    "numpy==2.2.2",
    "pyqt6>=6.8.1",
    "pytest",
    "pyyaml>=6.0.2",
    "ruff>=0.9.4",
    "tsplib95==0.7.1",
]
[tool.ruff.lint]
ignore = ["E741"]
